spring:
 application:
  name: service-zuul-server
server:
 port: 8090
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/
zuul:
 routes:
  store:
   service-id: service-store
   path: /api/tienda/**
  instance:
   service-id: springboot-service-prueba
   path: /api/phone/**
  user:
   service-id: SPRINGBOOT-SERVICE-COMMONS-USERS
   path: /api/us/**
  oauth:
   service-id: demo
   path: /api/security/**
   sensitive-headers: Cookie, Set-Cookie
ribbon:
 ConnectTimeout: 3000
 ReadTimeout: 10000
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 40000